import type { CommandEnvelope } from "../../../contracts/commands/CommandEnvelope.js";
import type {
  CompanyId,
  TripId
} from "../../../contracts/ids/EntityIds.js";
import { DomainError } from "../../../core/errors/DomainError.js";
import { err, ok, type Result } from "../../../core/result/Result.js";
import { gameDayAt } from "../../../core/time/GameTime.js";
import type { Driver } from "../../../domain/staff/Driver.js";
import {
  releaseDriverFromTrip,
  reserveDriverForTrip,
  startDriverTrip
} from "../../../domain/staff/DriverAssignmentRules.js";
import { generateDepartureSlots } from "../../../domain/schedule/ScheduleExpander.js";
import type { ServicePlan } from "../../../domain/schedule/ServicePlan.js";
import type { TripInstance } from "../../../domain/trip/TripInstance.js";
import {
  assignDriverToTrip,
  assignVehicleToTrip,
  cancelTrip,
  departTrip,
  prepareTrip,
  startTripBoarding
} from "../../../domain/trip/TripRules.js";
import type { OwnedVehicle } from "../../../domain/vehicle/OwnedVehicle.js";
import {
  releaseVehicleFromTrip,
  reserveVehicleForTrip,
  startVehicleTrip
} from "../../../domain/vehicle/VehicleAssignmentRules.js";
import type { CommandBus } from "../../CommandBus.js";
import type {
  AssignTripDriverPayload,
  AssignTripVehiclePayload,
  PrepareTripPayload,
  TripByIdPayload
} from "../../commands/trip/TripCommands.js";
import type { DomainEventBus } from "../../events/DomainEventBus.js";
import { createDomainEvent } from "../../events/createDomainEvent.js";
import type { RuntimeIdAllocator } from "../../ids/RuntimeIdAllocator.js";
import type { RepositoryBundle } from "../../repositories/RepositoryBundle.js";

export interface TripHandlerDependencies {
  readonly repositories: RepositoryBundle;
  readonly ids: RuntimeIdAllocator;
  readonly events: DomainEventBus;
}

export function registerTripHandlers(
  commands: CommandBus,
  dependencies: TripHandlerDependencies
): void {
  commands.register("trip.prepare", (command) =>
    handlePrepare(command, dependencies)
  );
  commands.register("trip.assignVehicle", (command) =>
    handleAssignVehicle(command, dependencies)
  );
  commands.register("trip.assignDriver", (command) =>
    handleAssignDriver(command, dependencies)
  );
  commands.register("trip.startBoarding", (command) =>
    handleStartBoarding(command, dependencies)
  );
  commands.register("trip.depart", (command) =>
    handleDepart(command, dependencies)
  );
  commands.register("trip.cancel", (command) =>
    handleCancel(command, dependencies)
  );
}

function handlePrepare(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as PrepareTripPayload;
  const plan = dependencies.repositories.servicePlans.getById(
    payload.servicePlanId
  );

  if (!plan || plan.status !== "active") {
    return err(
      new DomainError(
        "SERVICE_PLAN_INACTIVE",
        "Trip requires an active service plan",
        { servicePlanId: payload.servicePlanId }
      )
    );
  }

  const route = dependencies.repositories.routes.getById(plan.routeId);
  if (!route || route.status !== "active") {
    return err(
      new DomainError(
        "ROUTE_INACTIVE",
        "Trip requires an active route",
        { routeId: plan.routeId }
      )
    );
  }

  const actorCheck = requireActor(command, route.companyId);
  if (!actorCheck.ok) return actorCheck;

  const gameDay = gameDayAt(payload.plannedDepartureGameSecond);
  const slots = generateDepartureSlots(plan, gameDay);
  if (!slots.ok) return slots;

  const isOfficialSlot = slots.value.some(
    (slot) =>
      slot.plannedDepartureGameSecond ===
      payload.plannedDepartureGameSecond
  );

  if (!isOfficialSlot) {
    return err(
      new DomainError(
        "DEPARTURE_SLOT_INVALID",
        "Requested departure is not generated by the service plan",
        {
          servicePlanId: plan.id,
          plannedDepartureGameSecond: payload.plannedDepartureGameSecond
        }
      )
    );
  }

  const duplicate =
    dependencies.repositories.trips.findByServicePlanAndDeparture(
      plan.id,
      payload.plannedDepartureGameSecond
    );

  if (duplicate) {
    return err(
      new DomainError(
        "DUPLICATE_ID",
        "Trip already exists for this departure slot",
        { tripId: duplicate.id }
      )
    );
  }

  const prepared = prepareTrip({
    id: dependencies.ids.nextTripId(),
    routeId: route.id,
    servicePlanId: plan.id,
    plannedDepartureGameSecond: payload.plannedDepartureGameSecond,
    createdAtGameSecond: command.issuedAtGameSecond
  });
  if (!prepared.ok) return prepared;

  dependencies.repositories.trips.save(prepared.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.created",
      "trip",
      prepared.value.id,
      {
        tripId: prepared.value.id,
        routeId: prepared.value.routeId,
        servicePlanId: prepared.value.servicePlanId,
        plannedDepartureGameSecond:
          prepared.value.plannedDepartureGameSecond
      }
    )
  );

  return prepared;
}

function handleAssignVehicle(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as AssignTripVehiclePayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const vehicle = dependencies.repositories.vehicles.getById(payload.vehicleId);
  if (!vehicle) {
    return err(
      new DomainError(
        "ENTITY_NOT_FOUND",
        "Vehicle does not exist",
        { vehicleId: payload.vehicleId }
      )
    );
  }

  if (vehicle.companyId !== context.value.companyId) {
    return err(
      new DomainError(
        "INVALID_ARGUMENT",
        "Vehicle belongs to another company",
        { vehicleId: vehicle.id }
      )
    );
  }

  const model = dependencies.repositories.vehicleModels.getById(vehicle.modelId);
  if (!model) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Vehicle references a missing model",
        { vehicleId: vehicle.id, vehicleModelId: vehicle.modelId }
      )
    );
  }

  const reserved = reserveVehicleForTrip(
    vehicle,
    model,
    context.value.trip.id,
    context.value.plan.requiredVehicleClass
  );
  if (!reserved.ok) return reserved;

  const updatedTrip = assignVehicleToTrip(
    context.value.trip,
    vehicle.id
  );
  if (!updatedTrip.ok) return updatedTrip;

  dependencies.repositories.vehicles.save(reserved.value);
  dependencies.repositories.trips.save(updatedTrip.value);

  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.vehicleAssigned",
      "trip",
      updatedTrip.value.id,
      {
        tripId: updatedTrip.value.id,
        vehicleId: vehicle.id
      }
    )
  );

  return updatedTrip;
}

function handleAssignDriver(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as AssignTripDriverPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const driver = dependencies.repositories.staff.getDriverById(payload.driverId);
  if (!driver) {
    return err(
      new DomainError(
        "ENTITY_NOT_FOUND",
        "Driver does not exist",
        { driverId: payload.driverId }
      )
    );
  }

  if (driver.companyId !== context.value.companyId) {
    return err(
      new DomainError(
        "INVALID_ARGUMENT",
        "Driver belongs to another company",
        { driverId: driver.id }
      )
    );
  }

  const reserved = reserveDriverForTrip(
    driver,
    context.value.trip.id,
    context.value.plan.requiredVehicleClass
  );
  if (!reserved.ok) return reserved;

  const updatedTrip = assignDriverToTrip(
    context.value.trip,
    driver.id
  );
  if (!updatedTrip.ok) return updatedTrip;

  dependencies.repositories.staff.saveDriver(reserved.value);
  dependencies.repositories.trips.save(updatedTrip.value);

  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.driverAssigned",
      "trip",
      updatedTrip.value.id,
      {
        tripId: updatedTrip.value.id,
        driverId: driver.id
      }
    )
  );

  return updatedTrip;
}

function handleStartBoarding(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as TripByIdPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const updated = startTripBoarding(context.value.trip);
  if (!updated.ok) return updated;

  dependencies.repositories.trips.save(updated.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.boardingStarted",
      "trip",
      updated.value.id,
      { tripId: updated.value.id }
    )
  );

  return updated;
}

function handleDepart(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as TripByIdPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const resources = requireAssignedResources(
    context.value.trip,
    dependencies.repositories
  );
  if (!resources.ok) return resources;

  const updatedTrip = departTrip(
    context.value.trip,
    command.issuedAtGameSecond
  );
  if (!updatedTrip.ok) return updatedTrip;

  const runningVehicle = startVehicleTrip(
    resources.value.vehicle,
    context.value.trip.id
  );
  if (!runningVehicle.ok) return runningVehicle;

  const drivingDriver = startDriverTrip(
    resources.value.driver,
    context.value.trip.id
  );
  if (!drivingDriver.ok) return drivingDriver;

  dependencies.repositories.trips.save(updatedTrip.value);
  dependencies.repositories.vehicles.save(runningVehicle.value);
  dependencies.repositories.staff.saveDriver(drivingDriver.value);

  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.departed",
      "trip",
      updatedTrip.value.id,
      {
        tripId: updatedTrip.value.id,
        vehicleId: updatedTrip.value.vehicleId,
        driverId: updatedTrip.value.driverId,
        delaySeconds: updatedTrip.value.delaySeconds
      }
    )
  );

  return updatedTrip;
}

function handleCancel(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as TripByIdPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const cancelled = cancelTrip(context.value.trip);
  if (!cancelled.ok) return cancelled;

  if (context.value.trip.vehicleId !== null) {
    const vehicle = dependencies.repositories.vehicles.getById(
      context.value.trip.vehicleId
    );
    if (vehicle) {
      dependencies.repositories.vehicles.save(
        releaseVehicleFromTrip(vehicle, context.value.trip.id)
      );
    }
  }

  if (context.value.trip.driverId !== null) {
    const driver = dependencies.repositories.staff.getDriverById(
      context.value.trip.driverId
    );
    if (driver) {
      dependencies.repositories.staff.saveDriver(
        releaseDriverFromTrip(driver, context.value.trip.id)
      );
    }
  }

  dependencies.repositories.trips.save(cancelled.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.cancelled",
      "trip",
      cancelled.value.id,
      { tripId: cancelled.value.id }
    )
  );

  return cancelled;
}

interface TripContext {
  readonly trip: TripInstance;
  readonly plan: ServicePlan;
  readonly companyId: CompanyId;
}

function requireTripContext(
  tripId: TripId,
  repositories: RepositoryBundle
): Result<TripContext, DomainError> {
  const trip = repositories.trips.getById(tripId);
  if (!trip) {
    return err(
      new DomainError("ENTITY_NOT_FOUND", "Trip does not exist", { tripId })
    );
  }

  if (trip.servicePlanId === null) {
    return err(
      new DomainError(
        "SERVICE_PLAN_INVALID",
        "Trip has no service plan",
        { tripId }
      )
    );
  }

  const plan = repositories.servicePlans.getById(trip.servicePlanId);
  if (!plan) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Trip references a missing service plan",
        { tripId, servicePlanId: trip.servicePlanId }
      )
    );
  }

  const route = repositories.routes.getById(trip.routeId);
  if (!route) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Trip references a missing route",
        { tripId, routeId: trip.routeId }
      )
    );
  }

  return ok({
    trip,
    plan,
    companyId: route.companyId
  });
}

function requireAssignedResources(
  trip: TripInstance,
  repositories: RepositoryBundle
): Result<
  { readonly vehicle: OwnedVehicle; readonly driver: Driver },
  DomainError
> {
  if (trip.vehicleId === null || trip.driverId === null) {
    return err(
      new DomainError(
        "TRIP_RESOURCE_NOT_ASSIGNED",
        "Trip does not have both assigned resources",
        { tripId: trip.id }
      )
    );
  }

  const vehicle = repositories.vehicles.getById(trip.vehicleId);
  const driver = repositories.staff.getDriverById(trip.driverId);

  if (!vehicle || !driver) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Assigned vehicle or driver is missing",
        { tripId: trip.id }
      )
    );
  }

  return ok({ vehicle, driver });
}

function requireActor(
  command: CommandEnvelope,
  companyId: CompanyId
): Result<true, DomainError> {
  if (
    command.actorCompanyId !== undefined &&
    command.actorCompanyId !== companyId
  ) {
    return err(
      new DomainError(
        "INVALID_ARGUMENT",
        "Command actor does not own this operation",
        { companyId, actorCompanyId: command.actorCompanyId }
      )
    );
  }

  return ok(true);
}
