import type { CommandEnvelope } from "../../../contracts/commands/CommandEnvelope.js";
import type {
  CompanyId,
  StationId,
  TripId
} from "../../../contracts/ids/EntityIds.js";
import { DomainError } from "../../../core/errors/DomainError.js";
import { err, ok, type Result } from "../../../core/result/Result.js";
import { gameDayAt } from "../../../core/time/GameTime.js";
import type { Driver } from "../../../domain/staff/Driver.js";
import {
  beginDriverBoarding,
  releaseDriverFromTrip,
  startDriverTrip,
  validateDriverQualification
} from "../../../domain/staff/DriverAssignmentRules.js";
import { generateDepartureSlots } from "../../../domain/schedule/ScheduleExpander.js";
import type { ServicePlan } from "../../../domain/schedule/ServicePlan.js";
import type { TripInstance } from "../../../domain/trip/TripInstance.js";
import {
  assignDriverToTrip,
  assignVehicleToTrip,
  cancelTrip,
  clearTripResources,
  departTrip,
  prepareTrip,
  resumeDisruptedTrip,
  startTripBoarding
} from "../../../domain/trip/TripRules.js";
import type { OwnedVehicle } from "../../../domain/vehicle/OwnedVehicle.js";
import {
  validateVehicleDispatchReadiness,
  validateVehicleResumeReadiness
} from "../../../domain/vehicle/VehicleLifecycleRules.js";
import {
  beginVehicleBoarding,
  releaseVehicleFromTrip,
  startVehicleTrip,
  validateVehicleQualification
} from "../../../domain/vehicle/VehicleAssignmentRules.js";
import { serveRouteStop } from "../../../simulation/passenger/PassengerFlow.js";
import type { CommandBus } from "../../CommandBus.js";
import type {
  AssignTripDriverPayload,
  AssignTripVehiclePayload,
  ClearTripResourcesPayload,
  PrepareTripPayload,
  ResumeTripPayload,
  TripByIdPayload
} from "../../commands/trip/TripCommands.js";
import type { DomainEventBus } from "../../events/DomainEventBus.js";
import { createDomainEvent } from "../../events/createDomainEvent.js";
import type { RuntimeIdAllocator } from "../../ids/RuntimeIdAllocator.js";
import type { OperationsPolicy } from "../../policies/OperationsPolicy.js";
import type { RepositoryBundle } from "../../repositories/RepositoryBundle.js";
import { DispatchPlanningService } from "../../services/DispatchPlanningService.js";

export interface TripHandlerDependencies {
  readonly repositories: RepositoryBundle;
  readonly ids: RuntimeIdAllocator;
  readonly events: DomainEventBus;
  readonly operationsPolicy: OperationsPolicy;
}

export function registerTripHandlers(
  commands: CommandBus,
  dependencies: TripHandlerDependencies
): void {
  const dispatch = new DispatchPlanningService(
    dependencies.repositories,
    dependencies.operationsPolicy
  );

  commands.register("trip.prepare", (command) =>
    handlePrepare(command, dependencies)
  );
  commands.register("trip.assignVehicle", (command) =>
    handleAssignVehicle(command, dependencies, dispatch)
  );
  commands.register("trip.assignDriver", (command) =>
    handleAssignDriver(command, dependencies, dispatch)
  );
  commands.register("trip.clearResources", (command) =>
    handleClearResources(command, dependencies)
  );
  commands.register("trip.startBoarding", (command) =>
    handleStartBoarding(command, dependencies)
  );
  commands.register("trip.depart", (command) =>
    handleDepart(command, dependencies)
  );
  commands.register("trip.resume", (command) =>
    handleResume(command, dependencies)
  );
  commands.register("trip.cancel", (command) =>
    handleCancel(command, dependencies)
  );
}

function handlePrepare(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as PrepareTripPayload;
  const plan = dependencies.repositories.servicePlans.getById(
    payload.servicePlanId
  );

  if (!plan || plan.status !== "active") {
    return err(
      new DomainError(
        "SERVICE_PLAN_INACTIVE",
        "Trip requires an active service plan",
        { servicePlanId: payload.servicePlanId }
      )
    );
  }

  const route = dependencies.repositories.routes.getById(plan.routeId);
  if (!route || route.status !== "active") {
    return err(
      new DomainError(
        "ROUTE_INACTIVE",
        "Trip requires an active route",
        { routeId: plan.routeId }
      )
    );
  }

  const actorCheck = requireActor(command, route.companyId);
  if (!actorCheck.ok) return actorCheck;

  const slots = generateDepartureSlots(
    plan,
    gameDayAt(payload.plannedDepartureGameSecond)
  );
  if (!slots.ok) return slots;

  if (
    !slots.value.some(
      (slot) =>
        slot.plannedDepartureGameSecond ===
        payload.plannedDepartureGameSecond
    )
  ) {
    return err(
      new DomainError(
        "DEPARTURE_SLOT_INVALID",
        "Requested departure is not generated by the service plan",
        {
          servicePlanId: plan.id,
          plannedDepartureGameSecond: payload.plannedDepartureGameSecond
        }
      )
    );
  }

  const duplicate =
    dependencies.repositories.trips.findByServicePlanAndDeparture(
      plan.id,
      payload.plannedDepartureGameSecond
    );
  if (duplicate) {
    return err(
      new DomainError(
        "DUPLICATE_ID",
        "Trip already exists for this departure slot",
        { tripId: duplicate.id }
      )
    );
  }

  const prepared = prepareTrip({
    id: dependencies.ids.nextTripId(),
    routeId: route.id,
    servicePlanId: plan.id,
    plannedDepartureGameSecond: payload.plannedDepartureGameSecond,
    createdAtGameSecond: command.issuedAtGameSecond
  });
  if (!prepared.ok) return prepared;

  dependencies.repositories.trips.save(prepared.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.created",
      "trip",
      prepared.value.id,
      {
        tripId: prepared.value.id,
        routeId: prepared.value.routeId,
        servicePlanId: prepared.value.servicePlanId,
        plannedDepartureGameSecond:
          prepared.value.plannedDepartureGameSecond
      }
    )
  );

  return prepared;
}

function handleAssignVehicle(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies,
  dispatch: DispatchPlanningService
): Result<TripInstance, DomainError> {
  const payload = command.payload as AssignTripVehiclePayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const vehicle = dependencies.repositories.vehicles.getById(payload.vehicleId);
  if (!vehicle) {
    return err(
      new DomainError(
        "ENTITY_NOT_FOUND",
        "Vehicle does not exist",
        { vehicleId: payload.vehicleId }
      )
    );
  }
  if (vehicle.companyId !== context.value.companyId) {
    return err(
      new DomainError(
        "INVALID_ARGUMENT",
        "Vehicle belongs to another company",
        { vehicleId: vehicle.id }
      )
    );
  }

  const model = dependencies.repositories.vehicleModels.getById(vehicle.modelId);
  if (!model) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Vehicle references a missing model",
        { vehicleId: vehicle.id, vehicleModelId: vehicle.modelId }
      )
    );
  }

  const qualified = validateVehicleQualification(
    vehicle,
    model,
    context.value.plan.requiredVehicleClass
  );
  if (!qualified.ok) return qualified;

  if (context.value.trip.status === "planned") {
    const reservation = dispatch.validateVehicleReservation(
      context.value.trip,
      vehicle,
      model
    );
    if (!reservation.ok) return reservation;
  } else {
    const station = context.value.trip.recoveryStationId;
    if (
      station === null ||
      vehicle.currentStationId !== station ||
      vehicle.status !== "available" ||
      vehicle.activeTripId !== null ||
      vehicle.activeFleetTaskId !== null ||
      Number(vehicle.availableAtGameSecond) >
        Number(command.issuedAtGameSecond)
    ) {
      return err(
        new DomainError(
          "RESOURCE_LOCATION_MISMATCH",
          "Replacement vehicle is not available at the recovery station",
          { vehicleId: vehicle.id, recoveryStationId: station }
        )
      );
    }
  }

  const updatedTrip = assignVehicleToTrip(
    context.value.trip,
    vehicle.id
  );
  if (!updatedTrip.ok) return updatedTrip;

  dependencies.repositories.trips.save(updatedTrip.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.vehicleAssigned",
      "trip",
      updatedTrip.value.id,
      { tripId: updatedTrip.value.id, vehicleId: vehicle.id }
    )
  );
  return updatedTrip;
}

function handleAssignDriver(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies,
  dispatch: DispatchPlanningService
): Result<TripInstance, DomainError> {
  const payload = command.payload as AssignTripDriverPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  if (context.value.trip.vehicleId === null) {
    return err(
      new DomainError(
        "TRIP_RESOURCE_NOT_ASSIGNED",
        "Vehicle must be reserved before assigning a driver",
        { tripId: context.value.trip.id }
      )
    );
  }

  const vehicle = dependencies.repositories.vehicles.getById(
    context.value.trip.vehicleId
  );
  const model = vehicle
    ? dependencies.repositories.vehicleModels.getById(vehicle.modelId)
    : undefined;
  if (!vehicle || !model) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Reserved vehicle or vehicle model is missing",
        { tripId: context.value.trip.id }
      )
    );
  }

  const driver = dependencies.repositories.staff.getDriverById(
    payload.driverId
  );
  if (!driver) {
    return err(
      new DomainError(
        "ENTITY_NOT_FOUND",
        "Driver does not exist",
        { driverId: payload.driverId }
      )
    );
  }
  if (driver.companyId !== context.value.companyId) {
    return err(
      new DomainError(
        "INVALID_ARGUMENT",
        "Driver belongs to another company",
        { driverId: driver.id }
      )
    );
  }

  const qualified = validateDriverQualification(
    driver,
    context.value.plan.requiredVehicleClass
  );
  if (!qualified.ok) return qualified;

  if (context.value.trip.status === "planned") {
    const reservation = dispatch.validateDriverReservation(
      context.value.trip,
      driver,
      model
    );
    if (!reservation.ok) return reservation;
  } else {
    const station = context.value.trip.recoveryStationId;
    if (
      station === null ||
      driver.currentStationId !== station ||
      driver.status !== "available" ||
      driver.activeTripId !== null ||
      driver.activeFleetTaskId !== null ||
      Number(driver.availableAtGameSecond) >
        Number(command.issuedAtGameSecond)
    ) {
      return err(
        new DomainError(
          "RESOURCE_LOCATION_MISMATCH",
          "Replacement driver is not available at the recovery station",
          { driverId: driver.id, recoveryStationId: station }
        )
      );
    }
  }

  const updatedTrip = assignDriverToTrip(
    context.value.trip,
    driver.id
  );
  if (!updatedTrip.ok) return updatedTrip;

  dependencies.repositories.trips.save(updatedTrip.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.driverAssigned",
      "trip",
      updatedTrip.value.id,
      { tripId: updatedTrip.value.id, driverId: driver.id }
    )
  );
  return updatedTrip;
}

function handleClearResources(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as ClearTripResourcesPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const cleared = clearTripResources(context.value.trip);
  if (!cleared.ok) return cleared;

  dependencies.repositories.trips.save(cleared.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.resourcesCleared",
      "trip",
      cleared.value.id,
      { tripId: cleared.value.id }
    )
  );

  return cleared;
}

function handleStartBoarding(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as TripByIdPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const resources = requireAssignedResources(
    context.value.trip,
    dependencies.repositories
  );
  if (!resources.ok) return resources;

  const model = dependencies.repositories.vehicleModels.getById(
    resources.value.vehicle.modelId
  );
  if (!model) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Assigned vehicle model is missing"
      )
    );
  }

  const origin = context.value.route.stopPoints[0]?.stationId;
  if (!origin) {
    return err(
      new DomainError("ROUTE_INVALID", "Route has no origin station")
    );
  }

  const readiness = validateVehicleDispatchReadiness(
    resources.value.vehicle,
    model,
    context.value.route,
    dependencies.repositories.world.get(),
    command.issuedAtGameSecond
  );
  if (!readiness.ok) return readiness;

  const vehicleLock = beginVehicleBoarding(
    resources.value.vehicle,
    context.value.trip.id,
    origin,
    command.issuedAtGameSecond
  );
  if (!vehicleLock.ok) return vehicleLock;

  const driverLock = beginDriverBoarding(
    resources.value.driver,
    context.value.trip.id,
    origin,
    command.issuedAtGameSecond,
    dependencies.operationsPolicy.minimumDriverRestSeconds(
      resources.value.driver.id
    )
  );
  if (!driverLock.ok) return driverLock;

  const boarding = startTripBoarding(context.value.trip);
  if (!boarding.ok) return boarding;

  const flow = serveRouteStop(
    boarding.value,
    context.value.route,
    0,
    resources.value.vehicle.seatCapacity,
    dependencies.repositories.passengerRuntime.get()
  );

  dependencies.repositories.vehicles.save(vehicleLock.value);
  dependencies.repositories.staff.saveDriver(driverLock.value);
  dependencies.repositories.trips.save(flow.trip);

  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.boardingStarted",
      "trip",
      flow.trip.id,
      { tripId: flow.trip.id },
      1
    )
  );

  if (flow.boardedCount > 0) {
    dependencies.events.publish(
      createDomainEvent(
        command,
        "passengers.boarded",
        "trip",
        flow.trip.id,
        {
          tripId: flow.trip.id,
          stationId: origin,
          count: flow.boardedCount,
          boardedGroups: flow.boardedGroups,
          leftWaitingCount: flow.leftWaitingCount
        },
        2
      )
    );
  }

  return ok(flow.trip);
}

function handleDepart(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as TripByIdPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const resources = requireAssignedResources(
    context.value.trip,
    dependencies.repositories
  );
  if (!resources.ok) return resources;

  const updatedTrip = departTrip(
    context.value.trip,
    command.issuedAtGameSecond
  );
  if (!updatedTrip.ok) return updatedTrip;

  const runningVehicle = startVehicleTrip(
    resources.value.vehicle,
    context.value.trip.id
  );
  if (!runningVehicle.ok) return runningVehicle;

  const drivingDriver = startDriverTrip(
    resources.value.driver,
    context.value.trip.id
  );
  if (!drivingDriver.ok) return drivingDriver;

  dependencies.repositories.trips.save(updatedTrip.value);
  dependencies.repositories.vehicles.save(runningVehicle.value);
  dependencies.repositories.staff.saveDriver(drivingDriver.value);

  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.departed",
      "trip",
      updatedTrip.value.id,
      {
        tripId: updatedTrip.value.id,
        vehicleId: updatedTrip.value.vehicleId,
        driverId: updatedTrip.value.driverId,
        delaySeconds: updatedTrip.value.delaySeconds
      }
    )
  );

  return updatedTrip;
}

function handleResume(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as ResumeTripPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  if (
    context.value.trip.status !== "disrupted" ||
    context.value.trip.recoveryStationId === null
  ) {
    return err(
      new DomainError(
        "TRIP_NOT_DISRUPTED",
        "Trip must be recovered to a station before resume",
        { tripId: context.value.trip.id }
      )
    );
  }

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  const resources = requireAssignedResources(
    context.value.trip,
    dependencies.repositories
  );
  if (!resources.ok) return resources;

  const model = dependencies.repositories.vehicleModels.getById(
    resources.value.vehicle.modelId
  );
  if (!model) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Replacement vehicle model is missing"
      )
    );
  }

  const readiness = validateVehicleResumeReadiness(
    resources.value.vehicle,
    model,
    context.value.route,
    dependencies.repositories.world.get(),
    command.issuedAtGameSecond,
    context.value.trip.position.activeRoadSegmentIndex,
    Number(context.value.trip.position.offsetOnSegmentM)
  );
  if (!readiness.ok) return readiness;

  const station = context.value.trip.recoveryStationId;
  const vehicleLock = beginVehicleBoarding(
    resources.value.vehicle,
    context.value.trip.id,
    station,
    command.issuedAtGameSecond
  );
  if (!vehicleLock.ok) return vehicleLock;

  const driverLock = beginDriverBoarding(
    resources.value.driver,
    context.value.trip.id,
    station,
    command.issuedAtGameSecond,
    dependencies.operationsPolicy.minimumDriverRestSeconds(
      resources.value.driver.id
    )
  );
  if (!driverLock.ok) return driverLock;

  const runningVehicle = startVehicleTrip(
    vehicleLock.value,
    context.value.trip.id
  );
  if (!runningVehicle.ok) return runningVehicle;

  const drivingDriver = startDriverTrip(
    driverLock.value,
    context.value.trip.id
  );
  if (!drivingDriver.ok) return drivingDriver;

  const resumed = resumeDisruptedTrip(
    context.value.trip,
    command.issuedAtGameSecond
  );
  if (!resumed.ok) return resumed;

  dependencies.repositories.vehicles.save(runningVehicle.value);
  dependencies.repositories.staff.saveDriver(drivingDriver.value);
  dependencies.repositories.trips.save(resumed.value);

  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.resumed",
      "trip",
      resumed.value.id,
      {
        tripId: resumed.value.id,
        vehicleId: resumed.value.vehicleId,
        driverId: resumed.value.driverId,
        stationId: station
      }
    )
  );

  return resumed;
}

function handleCancel(
  command: CommandEnvelope,
  dependencies: TripHandlerDependencies
): Result<TripInstance, DomainError> {
  const payload = command.payload as TripByIdPayload;
  const context = requireTripContext(payload.tripId, dependencies.repositories);
  if (!context.ok) return context;

  const actorCheck = requireActor(command, context.value.companyId);
  if (!actorCheck.ok) return actorCheck;

  if (context.value.trip.status === "running") {
    return err(
      new DomainError(
        "INVALID_STATE_TRANSITION",
        "A running trip must be stopped or recovered before cancellation",
        { tripId: context.value.trip.id }
      )
    );
  }

  if (
    context.value.trip.status === "disrupted" &&
    (context.value.trip.vehicleId !== null ||
      context.value.trip.driverId !== null)
  ) {
    return err(
      new DomainError(
        "INVALID_STATE_TRANSITION",
        "Recover disrupted resources before cancelling the trip",
        { tripId: context.value.trip.id }
      )
    );
  }

  const cancelled = cancelTrip(context.value.trip);
  if (!cancelled.ok) return cancelled;

  if (
    context.value.trip.status === "boarding" &&
    context.value.trip.vehicleId !== null &&
    context.value.trip.driverId !== null
  ) {
    const origin = context.value.route.stopPoints[0]?.stationId ?? null;
    const vehicle = dependencies.repositories.vehicles.getById(
      context.value.trip.vehicleId
    );
    const driver = dependencies.repositories.staff.getDriverById(
      context.value.trip.driverId
    );

    if (vehicle) {
      dependencies.repositories.vehicles.save(
        releaseVehicleFromTrip(
          vehicle,
          context.value.trip.id,
          origin,
          command.issuedAtGameSecond
        )
      );
    }
    if (driver) {
      dependencies.repositories.staff.saveDriver(
        releaseDriverFromTrip(
          driver,
          context.value.trip.id,
          origin,
          command.issuedAtGameSecond,
          0,
          command.issuedAtGameSecond
        )
      );
    }
  }

  dependencies.repositories.trips.save(cancelled.value);
  dependencies.events.publish(
    createDomainEvent(
      command,
      "trip.cancelled",
      "trip",
      cancelled.value.id,
      { tripId: cancelled.value.id }
    )
  );

  return cancelled;
}

interface TripContext {
  readonly trip: TripInstance;
  readonly plan: ServicePlan;
  readonly route: NonNullable<ReturnType<RepositoryBundle["routes"]["getById"]>>;
  readonly companyId: CompanyId;
}

function requireTripContext(
  tripId: TripId,
  repositories: RepositoryBundle
): Result<TripContext, DomainError> {
  const trip = repositories.trips.getById(tripId);
  if (!trip) {
    return err(
      new DomainError("ENTITY_NOT_FOUND", "Trip does not exist", { tripId })
    );
  }

  if (trip.servicePlanId === null) {
    return err(
      new DomainError(
        "SERVICE_PLAN_INVALID",
        "Trip has no service plan",
        { tripId }
      )
    );
  }

  const plan = repositories.servicePlans.getById(trip.servicePlanId);
  if (!plan) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Trip references a missing service plan",
        { tripId, servicePlanId: trip.servicePlanId }
      )
    );
  }

  const route = repositories.routes.getById(trip.routeId);
  if (!route) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Trip references a missing route",
        { tripId, routeId: trip.routeId }
      )
    );
  }

  return ok({
    trip,
    plan,
    route,
    companyId: route.companyId
  });
}

function requireAssignedResources(
  trip: TripInstance,
  repositories: RepositoryBundle
): Result<
  { readonly vehicle: OwnedVehicle; readonly driver: Driver },
  DomainError
> {
  if (trip.vehicleId === null || trip.driverId === null) {
    return err(
      new DomainError(
        "TRIP_RESOURCE_NOT_ASSIGNED",
        "Trip does not have both assigned resources",
        { tripId: trip.id }
      )
    );
  }

  const vehicle = repositories.vehicles.getById(trip.vehicleId);
  const driver = repositories.staff.getDriverById(trip.driverId);

  if (!vehicle || !driver) {
    return err(
      new DomainError(
        "REFERENCE_NOT_FOUND",
        "Assigned vehicle or driver is missing",
        { tripId: trip.id }
      )
    );
  }

  return ok({ vehicle, driver });
}

function requireActor(
  command: CommandEnvelope,
  companyId: CompanyId
): Result<true, DomainError> {
  if (
    command.actorCompanyId !== undefined &&
    command.actorCompanyId !== companyId
  ) {
    return err(
      new DomainError(
        "INVALID_ARGUMENT",
        "Command actor does not own this operation",
        { companyId, actorCompanyId: command.actorCompanyId }
      )
    );
  }

  return ok(true);
}
